import { fileURLToPath } from 'url';
import { readFileSync } from 'fs';

export function pathify(path: string): string {
  if (path.startsWith('file://')) {
    path = fileURLToPath(path);
  }
  return path;
}

export async function instantiateEmscriptenWasm<
  T extends EmscriptenWasm.Module,
>(
  factory: EmscriptenWasm.ModuleFactory<T>,
  path: string,
  workerJS: string = '',
): Promise<T> {
  // In Node 20+, fetch() is available but doesn't support file:// URLs.
  // Pre-load the WASM binary to prevent Emscripten from trying to fetch() it.
  const wasmPath = pathify(path);
  const wasmBinary = readFileSync(wasmPath);

  return factory({
    wasmBinary,
    locateFile(requestPath) {
      // The glue code generated by emscripten uses the original
      // file names of the worker file and the wasm binary.
      // These will have changed in the bundling process and
      // we need to inject them here.
      if (requestPath.endsWith('.wasm')) return wasmPath;
      if (requestPath.endsWith('.worker.js')) return pathify(workerJS);
      return requestPath;
    },
  });
}
